FurniApp/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFreamework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    public class AboutController : Controller
    {
        OurTeamManager ot = new OurTeamManager(new EfOurTeamDal());
        // GET: About
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult OurTeamAdd()
        {
            return PartialView();
        }

        public ActionResult OurTeamList()
        {
            var teamlist = ot.GetList();
            return View(teamlist);
        }
    }
}

FurniApp/Controllers/CartController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFreamework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    public class CartController : Controller
    {
        CartManager cm = new CartManager(new EfCartDal());
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CartList()
        {
            var cartlist = cm.GetList();
            return View(cartlist);
        }
        [HttpGet]
        public ActionResult CartAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CartAdd(Cart id)
        {
            cm.TAdd(id);
            return RedirectToAction("CartList");
        }
    }
}

FurniApp/Controllers/ContacController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFreamework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    public class ContacController : Controller
    {
        ContactManager cm = new ContactManager(new EfContactDal());
        // GET: Contac
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult SendMessage()
        {
            return PartialView();
        }
        public PartialViewResult SendMessage(Contact a)
        {
            cm.TAdd(a);
            return PartialView();
        }
    }
}

FurniApp/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult Page403()
        {
            Response.StatusCode = 403;
            Response.TrySkipIisCustomErrors = true;
            return View();
        }
        public ActionResult Page404()
        {
            Response.StatusCode = 404;
            Response.TrySkipIisCustomErrors = true;
            return View();
        }
    }
}

FurniApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

FurniApp/Controllers/LoginController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFreamework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FurniApp.Controllers
{
    public class LoginController : Controller
    {
        AdminManager sp = new AdminManager(new EfAdminDal());
        // GET: Admin
        [AllowAnonymous]
        [HttpGet]
        public ActionResult AdminLogin()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult AdminLogin(Admin p)
        {
            Context c = new Context();
            var admininfo = c.Admins.FirstOrDefault(x => x.Name == p.Name && x.Password == p.Password);
            if (admininfo != null)
            {
                FormsAuthentication.SetAuthCookie(admininfo.Name, false);
                Session["UserName"] = admininfo.Name.ToString();
                return RedirectToAction("AdminShopList", "Shop");
            }
            else
            {
                return RedirectToAction("AdminLogin", "Login");
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public ActionResult UserLogin()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult UserLogin(Admin p)
        {
            Context c = new Context();
            var userinfo = c.Admins.FirstOrDefault(x => x.Name == p.Name && x.Password == p.Password);
            if (userinfo != null)
            {
                FormsAuthentication.SetAuthCookie(userinfo.Name, false);
                Session["UserName"] = userinfo.Name.ToString();
                return RedirectToAction("Index", "Shop");
            }
            else
            {
                return RedirectToAction("UserLogin", "Login");
            }
        }

    }
}

FurniApp/Controllers/MailSubscribeController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFreamework;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    [AllowAnonymous]
    public class MailSubscribeController : Controller
    {
        MailSubscribeManager ms = new MailSubscribeManager(new EfMailSubscribeDal());
        // GET: MailSubscribe

        [HttpGet]
        public PartialViewResult AddMail()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult AddMail(MailSubscribe t)
        {
            ms.TAdd(t);
            return PartialView();
        }
    }
}

FurniApp/Controllers/ShopController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccesLayer.Concrete;
using DataAccesLayer.EntityFreamework;
using EntityLayer;
using PagedList;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FurniApp.Controllers
{
    public class ShopController : Controller
    {
        ShopManager sp = new ShopManager(new EfShopDal());

        // GET: Shop
        public ActionResult Index()
        {
           return View();
        }

        public PartialViewResult ShopList(int page = 1)
        {
           var shoplist = sp.GetList().ToPagedList(page, 3);
            return PartialView(shoplist);
        }

        public PartialViewResult Footer()
        {
            return PartialView();
        }

        public PartialViewResult MailSubscribe()
        {
            return PartialView();
        }
        public ActionResult AdminShopList()
        {
            var shoplist = sp.GetList();
            return View(shoplist);
        }
        [HttpGet]
        public ActionResult AddNewShop()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddNewShop(Shop s)
        {
            sp.TAdd(s);
            return RedirectToAction("AdminShopList");
        }
        public ActionResult ShopDelete(int id)
        {
            sp.ShopStatusFalseSp(id);
            return RedirectToAction("AdminShopList");
        }
        public ActionResult ShopStatusTrue(int id)
        {
            sp.ShopStatusTrueSp(id);
            return RedirectToAction("AdminShopList");
            
        }
        [HttpGet]
        public ActionResult ShopUpdates(int id)
        {
            Shop shop = sp.GetByID(id);
            return View(shop);
        }

        [HttpPost]
        public ActionResult ShopUpdates(Shop x) 
        {
                sp.ShopUpdate(x);
                return RedirectToAction("AdminShopList");
        }
    }
}

FurniApp/Views/About/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AboutLayout.cshtml";
}

FurniApp/Views/About/OurTeamAdd.cshtml
@{
    ViewBag.Title = "OurTeamAdd";
    Layout = "~/Views/Shared/_AboutLayout.cshtml";
}

FurniApp/Views/About/OurTeamList.cshtml
@{
    ViewBag.Title = "OurTeamList";
    Layout = "~/Views/Shared/_AboutLayout.cshtml";
}

FurniApp/Views/AdminLogin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLogin.cshtml";
}

<h2>Index</h2>

FurniApp/Views/Cart/CartAdd.cshtml
@{
    ViewBag.Title = "CartAdd";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
}

FurniApp/Views/Cart/CartList.cshtml
@model IEnumerable <EntityLayer.Cart>
@{
    ViewBag.Title = "CartList";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Untree.co">
    <link rel="shortcut icon" href="favicon.png">

    <meta name="description" content="" />
    <meta name="keywords" content="bootstrap, bootstrap4" />

    <!-- Bootstrap CSS -->
    <link href="~/furni-1.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/furni-1.0.0/https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="~/furni-1.0.0/css/tiny-slider.css" rel="stylesheet">
    <link href="~/furni-1.0.0/css/style.css" rel="stylesheet">
    <title>Furni Free Bootstrap 5 Template for Furniture and Interior Design Websites by Untree.co </title>
</head>
<body>

    <!-- Start Header/Navigation -->
    <!-- End Header/Navigation -->
    <!-- Start Hero Section -->
    <div class="hero">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-lg-5">
                    <div class="intro-excerpt">
                        <h1>Cart</h1>
                    </div>
                </div>
                <div class="col-lg-7">

                </div>
            </div>
        </div>
    </div>
    <!-- End Hero Section -->


    
    <div class="untree_co-section before-footer-section">
        
        <div class="container">
           
            <div class="row mb-5">
           


                <form class="col-md-12" method="post">
                   
                    <div class="site-blocks-table">
                       

                            <table class="table">

                                <thead>
                                    <tr>
                                        <th class="product-thumbnail">Image</th>
                                        <th class="product-name">Product</th>                                     
                                        <th class="product-quantity">Quantity</th>
                                        <th class="product-total">Price</th>
                                        <th class="product-remove">Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="product-thumbnail">
                                                <img src="@item.Image" alt="Image" class="img-fluid">
                                            </td>

                                            <td class="product-name">
                                                <h2 class="h5 text-black">@item.ProductName</h2>
                                            </td>

                                            <td>
                                                <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                                                    <div class="input-group-prepend">
                                                        <button class="btn btn-outline-black decrease" type="button">&minus;</button>
                                                    </div>
                                                    <input type="text" class="form-control text-center quantity-amount" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                                                    <div class="input-group-append">
                                                        <button class="btn btn-outline-black increase" type="button">&plus;</button>
                                                    </div>
                                                </div>

                                            </td>

                                            <td>$@item.ProductPrice</td>
                                            <td><a href="#" class="btn btn-black btn-sm">X</a></td>

                                        </tr>
}
                                </tbody>
                            </table>
                        </div> 
                    </form>
                </div>
            </div>
        </div>
        <!-- Start Footer Section -->
        <!-- End Footer Section -->


        <script src="~/furni-1.0.0/js/bootstrap.bundle.min.js"></script>
        <script src="~/furni-1.0.0/js/tiny-slider.js"></script>
        <script src="~/furni-1.0.0/js/custom.js"></script>
    </body>
            
</html>

FurniApp/Views/Cart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
}

<h2>Index</h2>

FurniApp/Views/Contac/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ContactLayout.cshtml";
}

FurniApp/Views/Contac/SendMessage.cshtml
@{
    ViewBag.Title = "SendMessage";
    Layout = "~/Views/Shared/_ContactLayout.cshtml";
}

FurniApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

FurniApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

FurniApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

FurniApp/Views/Login/AdminLogin.cshtml
@{
    Layout = null;
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>Report Login Form Responsive Widget Template :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords"
          content="Report Login Form Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <!-- //Meta tag Keywords -->
    <link href="//fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap" rel="stylesheet">
    <!--/Style-CSS -->
    <link rel="stylesheet" href="~/Report-Login-Free/css/style.css" type="text/css" media="all" />
    <!--//Style-CSS -->
    <link rel="stylesheet" href="/Report-Login-Free/css/font-awesome.min.css" type="text/css" media="all">
</head>
<body>
    <!-- form section start -->
    <section class="w3l-hotair-form">
        <h1>Furni Giriş</h1>
        <div class="container">
            <!-- /form -->
            <div class="workinghny-form-grid">
                <div class="main-hotair">
                    <div class="content-wthree">
                        <h2>Login Paneli</h2>
                        @using (Html.BeginForm("AdminLogin", "Login", FormMethod.Post))
                        {
                            <input type="text" class="text" name="Name" placeholder="Mail Adresi" required="" autofocus>
                            <input type="password" class="password" name="Password" placeholder="Şifre" required="" autofocus>
                            <button class="btn" type="submit">Giriş Yap</button>
                        }
                        <p class="account">Şifremi unuttum? <a href="#signup">Şifre gönder</a></p>
                        <p class="account">User Girişi <a href="/Login/UserLogin/">Giriş Sayfası</a></p>
                    </div>
                    <div class="w3l_form align-self">
                        <div class="left_grid_info">
                            <img src="~/Report-Login-Free/images/1.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
            <!-- //form -->
        </div>
        <!-- copyright-->
        <div class="copyright text-center">
            <p class="copy-footer-29">
                © 2021 Report Login Form. Tüm hakları saklıdır | Design by <a href="https://w3layouts.com">W3layouts</a>
            </p>
        </div>
        <!-- //copyright-->
    </section>
    <!-- //form section start -->
</body>

</html>

FurniApp/Views/Login/UserLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>


<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>Report Login Form Responsive Widget Template :: W3layouts</title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords"
          content="Report Login Form Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <!-- //Meta tag Keywords -->
    <link href="//fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;700;900&display=swap" rel="stylesheet">
    <!--/Style-CSS -->
    <link rel="stylesheet" href="~/Report-Login-Free/css/style.css" type="text/css" media="all" />
    <!--//Style-CSS -->
    <link rel="stylesheet" href="/Report-Login-Free/css/font-awesome.min.css" type="text/css" media="all">
</head>
<body>
    <!-- form section start -->
    <section class="w3l-hotair-form">
        <h1>Furni Giriş</h1>
        <div class="container">
            <!-- /form -->
            <div class="workinghny-form-grid">
                <div class="main-hotair">
                    <div class="content-wthree">
                        <h2>Login Paneli</h2>
                        @using (Html.BeginForm("UserLogin", "Login", FormMethod.Post))
                        {
                            <input type="text" class="text" name="Name" placeholder="Mail Adresi" required="" autofocus>
                            <input type="password" class="password" name="Password" placeholder="Şifre" required="" autofocus>
                            <button class="btn" type="submit">Giriş Yap</button>
                        }
                        <p class="account">Şifremi unuttum? <a href="#signup">Şifre gönder</a></p>
                        <p class="account">Admin Girişi <a href="/Login/AdminLogin/">Giriş Sayfası</a></p>
                    </div>
                    <div class="w3l_form align-self">
                        <div class="left_grid_info">
                            <img src="~/Report-Login-Free/images/1.png" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
            <!-- //form -->
        </div>
        <!-- copyright-->
        <div class="copyright text-center">
            <p class="copy-footer-29">
                © 2021 Report Login Form. Tüm hakları saklıdır | Design by <a href="https://w3layouts.com">W3layouts</a>
            </p>
        </div>
        <!-- //copyright-->
    </section>
    <!-- //form section start -->
</body>
</html>

FurniApp/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FurniApp/Views/Shared/_AdminLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Projects</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="../../index3.html" class="brand-link">
                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png"
                     alt="Admin Lte Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Blog Yazar Paneli</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Hoş Geldiniz</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="/User/BlogList/" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Ürünlerim
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/Blog/Index/" class="nav-link">
                                <i class="nav-icon fas fa-blog"></i>
                                <p>
                                    Ürün Hızlı Bakış
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/User/Index/" class="nav-link">
                                <i class="nav-icon fas fa-address-card"></i>
                                <p>
                                    Profilimi Düzenle
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/User/LogOut/" class="nav-link">
                                <i class="nav-icon fas fa-car"></i>
                                <p>
                                    Çıkış Yap
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">

                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </section>
            <!-- Main content -->
            <!-- /.content -->
        </div>
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

FurniApp/Views/Shop/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Action("ShopList", "Shop")
@Html.Action("AddMail", "MailSubscribe")